from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict

from ..workspace import Workspace
from .errors import ApprovalError
from .ids import parse_typed_id, utc_now
from .models import ApprovalRecord, ExecutionPlan, ExecutionRecord
from .store import EGCFStore


class ApprovalManager:
    def __init__(self, store: EGCFStore, workspace: Workspace):
        self.store = store
        self.workspace = workspace

    def authorize(
        self,
        plan_id: str,
        *,
        approver: str,
        authority: str,
        constraints: Dict[str, Any] | None = None,
        expires_at: str = "",
        human: bool = True,
        use_limit: int = 1,
    ) -> str:
        plan = self.store.get(plan_id)
        if not isinstance(plan, ExecutionPlan):
            raise ApprovalError(f"not an execution plan: {plan_id}")
        if not human:
            raise ApprovalError("human approval records cannot be generated by a model or workflow")
        if not approver.strip() or not authority.strip():
            raise ApprovalError("approval requires an approver and external authority statement")
        if plan.source_snapshot_hash != self.workspace.snapshot_hash():
            raise ApprovalError("execution plan source snapshot is stale")
        _, plan_digest = parse_typed_id(plan_id)
        record = ApprovalRecord(
            plan_id=plan_id,
            plan_hash=plan_digest,
            approver=approver,
            authority=authority,
            constraints=dict(constraints or {}),
            created_at=utc_now(),
            expires_at=expires_at,
            use_limit=max(1, min(int(use_limit), 20)),
            human=True,
        )
        return self.store.register(record, event_type="egcf_human_approval")

    @staticmethod
    def _expired(expires_at: str) -> bool:
        if not expires_at:
            return False
        expiry = datetime.fromisoformat(expires_at.replace("Z", "+00:00"))
        if expiry.tzinfo is None:
            expiry = expiry.replace(tzinfo=timezone.utc)
        return expiry <= datetime.now(timezone.utc)

    def validate(self, plan: ExecutionPlan, approval_id: str) -> ApprovalRecord:
        approval = self.store.get(approval_id)
        if not isinstance(approval, ApprovalRecord):
            raise ApprovalError(f"not an approval record: {approval_id}")
        if approval.plan_id != plan.object_id:
            raise ApprovalError("approval is bound to a different execution plan")
        _, expected_digest = parse_typed_id(plan.object_id)
        if approval.plan_hash != expected_digest:
            raise ApprovalError("approval plan hash does not match the execution plan")
        if not approval.human:
            raise ApprovalError("human approval is required")
        if self._expired(approval.expires_at):
            raise ApprovalError("approval has expired")
        if plan.source_snapshot_hash != self.workspace.snapshot_hash():
            raise ApprovalError("source snapshot changed after approval")
        prior_uses = len(
            self.store.find(
                "execution",
                lambda item: isinstance(item, ExecutionRecord)
                and item.plan_id == plan.object_id
                and item.node_id == "__workflow__"
                and item.status in {"COMPLETED", "SIMULATED"},
            )
        )
        if prior_uses >= approval.use_limit:
            raise ApprovalError("approval use limit is exhausted")
        return approval
