"""Public facade for SAA-8 reasoning algorithms, topology equivalence and semantic state gates."""

from .algebra.reasoning import (
    MAX_REASONING_CANONICAL_PERMUTATIONS,
    MAX_REASONING_EDGES,
    MAX_REASONING_NODES,
    MAX_REASONING_STEPS,
    REASONING_ALGEBRA_VERSION,
    REASONING_EDGE_RELATIONS,
    REASONING_OPERATORS,
    CanonicalReasoningAlgorithm,
    ReasoningAlgorithmSpec,
    ReasoningEdgeSpec,
    ReasoningNodeSpec,
    ReasoningTerminationSpec,
    canonicalize_reasoning_algorithm,
)
from .algebra.reasoning_equivalence import (
    REASONING_EQUIVALENCE_VERSION,
    ReasoningEquivalenceAssessment,
    ReasoningTopologyDelta,
    compare_reasoning_algorithms,
    reasoning_topology_delta,
)
from .algebra.reasoning_semantics import (
    REASONING_GOVERNANCE_SUBSYSTEMS,
    REASONING_SEMANTIC_VERSION,
    ReasoningSemanticAssessment,
    ReasoningSemanticDirective,
    ReasoningSemanticIssue,
    ReasoningStateDependency,
    ReasoningStateDimension,
    ReasoningStateModel,
    assess_reasoning_state_semantics,
    propagate_reasoning_semantic_issues,
)

__all__ = [
    "MAX_REASONING_CANONICAL_PERMUTATIONS",
    "MAX_REASONING_EDGES",
    "MAX_REASONING_NODES",
    "MAX_REASONING_STEPS",
    "REASONING_ALGEBRA_VERSION",
    "REASONING_EDGE_RELATIONS",
    "REASONING_EQUIVALENCE_VERSION",
    "REASONING_GOVERNANCE_SUBSYSTEMS",
    "REASONING_OPERATORS",
    "REASONING_SEMANTIC_VERSION",
    "CanonicalReasoningAlgorithm",
    "ReasoningAlgorithmSpec",
    "ReasoningEdgeSpec",
    "ReasoningEquivalenceAssessment",
    "ReasoningNodeSpec",
    "ReasoningSemanticAssessment",
    "ReasoningSemanticDirective",
    "ReasoningSemanticIssue",
    "ReasoningStateDependency",
    "ReasoningStateDimension",
    "ReasoningStateModel",
    "ReasoningTerminationSpec",
    "ReasoningTopologyDelta",
    "assess_reasoning_state_semantics",
    "canonicalize_reasoning_algorithm",
    "compare_reasoning_algorithms",
    "propagate_reasoning_semantic_issues",
    "reasoning_topology_delta",
]
