"""Searchable Algebra of Algorithms canonicalization layers."""

from .dynamics import (
    DYNAMICS_VERSION,
    LINEAR_DOMAINS,
    MAX_POLYNOMIAL_DEGREE,
    MAX_STATE_ORDER,
    CanonicalLinearDynamics,
    LinearStateSpace,
    LinearTransferFunction,
    canonicalize_state_space,
    canonicalize_transfer_function,
    dynamic_algorithm_signature,
)
from .graph import CANONICALIZER_VERSION, canonicalize_structure, validate_structure
from .ir import canonicalize_many, canonicalize_mapping, operand_from_mapping, structure_from_mapping
from .models import (
    AlgorithmNodeSpec,
    AlgorithmStructureSpec,
    CanonicalAlgorithmIR,
    ControlEdgeSpec,
    OperandRef,
    PortSpec,
    StateSpec,
    attribute_items,
)
from .normalize import (
    BOUND_KINDS,
    EXACT_BOUND_KINDS,
    NORMALIZER_VERSION,
    NormalizationBinding,
    NormalizationContract,
    NumericBound,
    TimeNormalization,
    build_normalization_contract,
    denormalize_role,
    denormalize_time,
    denormalize_value,
    normalize_role,
    normalize_time,
    normalize_value,
    normalized_algorithm_signature,
    numeric_bound,
    time_normalization,
)
from .primitives import PrimitiveSpec, normalize_primitive, primitive_names

__all__ = [
    "AlgorithmNodeSpec",
    "AlgorithmStructureSpec",
    "BOUND_KINDS",
    "CANONICALIZER_VERSION",
    "CanonicalAlgorithmIR",
    "CanonicalLinearDynamics",
    "ControlEdgeSpec",
    "DYNAMICS_VERSION",
    "EXACT_BOUND_KINDS",
    "LINEAR_DOMAINS",
    "LinearStateSpace",
    "LinearTransferFunction",
    "MAX_POLYNOMIAL_DEGREE",
    "MAX_STATE_ORDER",
    "NORMALIZER_VERSION",
    "NormalizationBinding",
    "NormalizationContract",
    "NumericBound",
    "OperandRef",
    "PortSpec",
    "PrimitiveSpec",
    "StateSpec",
    "TimeNormalization",
    "attribute_items",
    "build_normalization_contract",
    "canonicalize_many",
    "canonicalize_mapping",
    "canonicalize_state_space",
    "canonicalize_structure",
    "canonicalize_transfer_function",
    "denormalize_role",
    "denormalize_time",
    "denormalize_value",
    "dynamic_algorithm_signature",
    "normalize_primitive",
    "normalize_role",
    "normalize_time",
    "normalize_value",
    "normalized_algorithm_signature",
    "numeric_bound",
    "operand_from_mapping",
    "primitive_names",
    "structure_from_mapping",
    "time_normalization",
    "validate_structure",
]
